### ISSUE TITLE
Дать оценку визуальным изменениям

### ISSUE THREAD

**Issue by lord-vesel** [lord-vesel/dcs-doc#42]
@alex-mos Оцени плз https://dcs-docs-dev.lordvesel.win/ru/, собранный из MR #41

Ок или не ок:

- Опциональная тёмная тема
- Вынос разделов в табы наверх
- Новая тема для клавиатурных шорткатов

**Comment by alex-mos** [comment]
Я думаю, что проекту нужен более масштабный редизайн (подробнее написал в телеграме), но совсем не против этого дополнения.

**Comment by lord-vesel** [comment]
Спасибо!
